/*
 * KAPED PARTNER API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ApplicationStatusUpdate model module.
 * @module model/ApplicationStatusUpdate
 * @version 1.0.1
 */
export class ApplicationStatusUpdate {
  /**
   * Constructs a new <code>ApplicationStatusUpdate</code>.
   * @alias module:model/ApplicationStatusUpdate
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ApplicationStatusUpdate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApplicationStatusUpdate} obj Optional instance to populate.
   * @return {module:model/ApplicationStatusUpdate} The populated <code>ApplicationStatusUpdate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ApplicationStatusUpdate();
      if (data.hasOwnProperty('applicationID'))
        obj.applicationID = ApiClient.convertToType(data['applicationID'], 'String');
      if (data.hasOwnProperty('sentToUnderwriting'))
        obj.sentToUnderwriting = ApiClient.convertToType(data['sentToUnderwriting'], 'Boolean');
      if (data.hasOwnProperty('reject'))
        obj.reject = ApiClient.convertToType(data['reject'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} applicationID
 */
ApplicationStatusUpdate.prototype.applicationID = undefined;

/**
 * @member {Boolean} sentToUnderwriting
 */
ApplicationStatusUpdate.prototype.sentToUnderwriting = undefined;

/**
 * @member {Boolean} reject
 */
ApplicationStatusUpdate.prototype.reject = undefined;

