/*
 * KAPED PARTNER API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.37
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * Enum class Gender.
 * @enum {String}
 * @readonly
 */
const Gender = {
  /**
   * value: "Male"
   * @const
   */
  male: "Male",

  /**
   * value: "Female"
   * @const
   */
  female: "Female",

  /**
   * value: "Transgender"
   * @const
   */
  transgender: "Transgender",

  /**
   * Returns a <code>Gender</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
  * @return {module:model/Gender} The enum <code>Gender</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {Gender};