/*
 * KAPED PARTNER API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SubmitApplication model module.
 * @module model/SubmitApplication
 * @version 1.0.1
 */
export class SubmitApplication {
  /**
   * Constructs a new <code>SubmitApplication</code>.
   * @alias module:model/SubmitApplication
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SubmitApplication</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubmitApplication} obj Optional instance to populate.
   * @return {module:model/SubmitApplication} The populated <code>SubmitApplication</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubmitApplication();
      if (data.hasOwnProperty('applicationType'))
        obj.applicationType = ApiClient.convertToType(data['applicationType'], 'String');
      if (data.hasOwnProperty('formData'))
        obj.formData = ApiClient.convertToType(data['formData'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} applicationType
 */
SubmitApplication.prototype.applicationType = undefined;

/**
 * @member {String} formData
 */
SubmitApplication.prototype.formData = undefined;

