/*
 * KAPED PARTNER API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KapedPartnerApi);
  }
}(this, function(expect, KapedPartnerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('EditApplication', function() {
      beforeEach(function() {
        instance = new KapedPartnerApi.EditApplication();
      });

      it('should create an instance of EditApplication', function() {
        // TODO: update the code to test EditApplication
        expect(instance).to.be.a(KapedPartnerApi.EditApplication);
      });

      it('should have the property applicationType (base name: "applicationType")', function() {
        // TODO: update the code to test the property applicationType
        expect(instance).to.have.property('applicationType');
        // expect(instance.applicationType).to.be(expectedValueLiteral);
      });

      it('should have the property formData (base name: "formData")', function() {
        // TODO: update the code to test the property formData
        expect(instance).to.have.property('formData');
        // expect(instance.formData).to.be(expectedValueLiteral);
      });

    });
  });

}));
