/*
 * KAPED PARTNER API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.37
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KapedPartnerApi);
  }
}(this, function(expect, KapedPartnerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Gender', function() {
      beforeEach(function() {
        instance = KapedPartnerApi.Gender;
      });

      it('should create an instance of Gender', function() {
        // TODO: update the code to test Gender
        expect(instance).to.be.a('object');
      });

      it('should have the property male', function() {
        expect(instance).to.have.property('male');
        expect(instance.male).to.be("Male");
      });

      it('should have the property female', function() {
        expect(instance).to.have.property('female');
        expect(instance.female).to.be("Female");
      });

      it('should have the property transgender', function() {
        expect(instance).to.have.property('transgender');
        expect(instance.transgender).to.be("Transgender");
      });

    });
  });

}));
