/*
 * KAPED PARTNER API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.37
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KapedPartnerApi);
  }
}(this, function(expect, KapedPartnerApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Ownership', function() {
      beforeEach(function() {
        instance = KapedPartnerApi.Ownership;
      });

      it('should create an instance of Ownership', function() {
        // TODO: update the code to test Ownership
        expect(instance).to.be.a('object');
      });

      it('should have the property _public', function() {
        expect(instance).to.have.property('_public');
        expect(instance._public).to.be("public");
      });

      it('should have the property _private', function() {
        expect(instance).to.have.property('_private');
        expect(instance._private).to.be("private");
      });

    });
  });

}));
