/*
 * KAPED PARTNER API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.36
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {ApplicationStatusUpdate} from './model/ApplicationStatusUpdate';
import {EditApplication} from './model/EditApplication';
import {Login} from './model/Login';
import {ResumeApplication} from './model/ResumeApplication';
import {SubmitApplication} from './model/SubmitApplication';
import {ViewCardDetail} from './model/ViewCardDetail';
import {RESTCallsApi} from './api/RESTCallsApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var KapedPartnerApi = require('index'); // See note below*.
* var xxxSvc = new KapedPartnerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new KapedPartnerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new KapedPartnerApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new KapedPartnerApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApplicationStatusUpdate model constructor.
     * @property {module:model/ApplicationStatusUpdate}
     */
    ApplicationStatusUpdate,

    /**
     * The EditApplication model constructor.
     * @property {module:model/EditApplication}
     */
    EditApplication,

    /**
     * The Login model constructor.
     * @property {module:model/Login}
     */
    Login,

    /**
     * The ResumeApplication model constructor.
     * @property {module:model/ResumeApplication}
     */
    ResumeApplication,

    /**
     * The SubmitApplication model constructor.
     * @property {module:model/SubmitApplication}
     */
    SubmitApplication,

    /**
     * The ViewCardDetail model constructor.
     * @property {module:model/ViewCardDetail}
     */
    ViewCardDetail,

    /**
    * The RESTCallsApi service constructor.
    * @property {module:api/RESTCallsApi}
    */
    RESTCallsApi
};
